divider = 63
buildCeiling = 24
buildFloor = 4
redSpawnX = 6
redSpawnY = 24
redSpawnZ = 96
redSpawnRotation=64,0
blueSpawnX = 121
blueSpawnY = 24
blueSpawnZ = 31
blueSpawnRotation=192,0
redFlagX = 15
redFlagY = 19
redFlagZ = 64
blueFlagX = 112
blueFlagY = 19
blueFlagZ = 63
solidBlocks = all
author = Shr3dd3r