divider = 31
buildCeiling = 82
redSpawnX = 21
redSpawnY = 76
redSpawnZ = 3
redSpawnRotation=64,0
blueSpawnX = 42
blueSpawnY = 76
blueSpawnZ = 60
blueSpawnRotation=192,0
redFlagX = 2
redFlagY = 71
redFlagZ = 61
blueFlagX = 61
blueFlagY = 71
blueFlagZ = 2
solidBlocks = 34 49 58 160
author = Shr3dd3r
texturepack=reduxCTFmapBuild
