#maps/archives.cw

#Misc
author=pascalos
texturepack=reduxCTFmapBuild

#Spawn/flag positions
blueFlagX=73
blueFlagY=66
blueFlagZ=27
blueSpawnX=81
blueSpawnY=64
blueSpawnZ=5
blueSpawnRotation=270
redFlagX=12
redFlagY=66
redFlagZ=27
redSpawnX=4
redSpawnY=64
redSpawnZ=49
redSpawnRotation=90
spawnPosition=42,82,27
spawnRotation=0

#Env settings
cloudHeight=-10000

#Gameplay
buildCeiling=75
divider=42




