divider = 48
buildCeiling = 85
redSpawnX = 1
redSpawnY = 72
redSpawnZ = 36
redSpawnRotation=64,0
blueSpawnX = 96
blueSpawnY = 72
blueSpawnZ = 61
blueSpawnRotation=192,0
redFlagX = 21
redFlagY = 75
redFlagZ = 71
blueFlagX = 76
blueFlagY = 75
blueFlagZ = 26
solidBlocks = 1 21 28 34
author = Shr3dd3r
texturepack=reduxCTFmapBuild
