divider = 48
buildCeiling = 85
buildFloor = 63
redSpawnX = 13
redSpawnY = 70
redSpawnZ = 67
redSpawnRotation=64,0
blueSpawnX = 84
blueSpawnY = 70
blueSpawnZ = 30
blueSpawnRotation=192,0
redFlagX = 11
redFlagY = 70
redFlagZ = 11
blueFlagX = 86
blueFlagY = 70
blueFlagZ = 86
solidBlocks = 21 29 34 255
author = Shr3dd3r
texturepack=reduxCTFmapBuild
