divider = 63
buildCeiling = 85
redSpawnX = 25
redSpawnY = 95
redSpawnZ = 61
redSpawnRotation=64,0
blueSpawnX = 100
blueSpawnY = 95
blueSpawnZ = 2
blueSpawnRotation=192,0
redFlagX = 13
redFlagY = 69
redFlagZ = 31
blueFlagX = 112
blueFlagY = 69
blueFlagZ = 32
solidBlocks = all
author = Shr3dd3r